name: Run Arxiv Papers Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "* 0/12 * * *" #'*/60 * * * *'    # 매 12시간마다 실행

  push:
    branches: [feature/branch-name]  # 특정 브랜치로 변경

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Seoul"
      RUN_ENV: "production" # within ['production', 'development']
      POWER: 16
    steps:
      # ============================================
      # TODO [√] 检查工作分支及 Workflows 运行环境
      # ============================================
      - name: Checkout
        uses: actions/checkout@v2
      # ============================================
      # TODO [√] 创建 Python3.6+ 编译环境
      # ============================================
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # ============================================
      # TODO [√] 安装 Project 第三方依赖
      # ============================================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # 여기 부분에 main.py 코드 전에 daily_arxiv.py 파일을 먼저 실행시킨 후 진행을 하면 12시간마다 db업데이트.
      # ============================================
      - name: Run daily_arxiv.py
        run: |
          python daily_arxiv_db.py run --env=${{ env.RUN_ENV }} --power=${{ env.POWER }} 
      # ============================================
      # TODO [√] 测试 Scaffold 脚手架指令
      # ============================================
      - name: Run daily arxiv
        run: |
          python main.py run --env=${{ env.RUN_ENV }} --power=${{ env.POWER }}
      # ============================================
      # TODO [√] 更新仓库数据
      # ======================================F======
      - name: Setup GIT user
        uses: fregante/setup-git-user@v1

      - name: Push done work
        run: |
          git diff --exit-code || git commit -am "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') ${{ env.TZ }}"
          git push origin feature/branch-name
      # ============================================
      # TODO [√] 更新 mkdocs
      # ============================================
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements-mkdocs.txt
